using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraSwitcher : MonoBehaviour
{
    public GameObject[] cameras;

    private int currentCamera;
    
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.C))
        {
            currentCamera++;

            if (currentCamera >= cameras.Length)
            {
                currentCamera = 0;
            }

            for (int i = 0; i < cameras.Length; i++)
            {
                if (currentCamera == i)
                {
                    cameras[i].SetActive(true);
                }
                else
                {
                    cameras[i].SetActive(false);
                }
            }
        }    
    }
}
